import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/HomePage/Navbar";
import ThemeProviders from "@/Providers/ThemeProviders";
import Footer from "@/Components/HomePage/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="bg-background text-foreground">
                <ThemeProviders>
                    <Navbar />
                    <main className="pt-24 md:pt-20 container mx-auto">
                      {children}
                    </main>
                    <Footer/>
                </ThemeProviders>
            </body>
        </html>
    );
}
